version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    # ports:
    #   - 5601:5601
    networks:
      - elastic

networks:
  elastic:
    external:
      name: elasticsearch_elastic