version: '2'
services:
  logstash:

    build: .
    # volumes:
      # - ./pipeline/csv-filter/csv_file.conf:/usr/share/logstash/pipeline/csv_file.conf
      # - ./pipeline/mutuate-filter/csv_file_mutuate.conf:/usr/share/logstash/pipeline/csv_file_mutuate.conf
      # - ./data-example/users.csv:/usr/share/logstash/data/users.csv
      # - ./pipeline/logstash_product.conf:/usr/share/logstash/pipeline/logstash_product.conf
      # - ./pipeline/logstash_products_with_features_features.conf:/usr/share/logstash/pipeline/logstash_products_with_features_features.conf
      # - ./pipeline/logstash_products_with_features_products.conf:/usr/share/logstash/pipeline/logstash_products_with_features_products.conf
      # - ./pipeline/logstash_network_traffic_data.conf:/usr/share/logstash/pipeline/logstash_network_traffic_data.conf
      # - ./data-example/products.csv:/usr/share/logstash/data/products.csv
      # - ./data-example/products_with_features_features.csv:/usr/share/logstash/data/products_with_features_features.csv
      # - ./data-example/products_with_features_products.csv:/usr/share/logstash/data/products_with_features_products.csv
      # - ./data-example/network_traffic_data.json:/usr/share/logstash/data/network_traffic_data.json
    # ports:
    #   - 5601:5601
    networks:
      - elastic

networks:
  elastic:
    external:
      name: elasticsearch_elastic